FROM python:3.9-slim

WORKDIR /app

COPY conf.json .
COPY requirements.txt .

# COPY deps /deps
# RUN pip install --no-cache-dir /deps/*

# RUN pip install --no-cache-dir -r requirements.txt

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . .
COPY redisConnect.py .

EXPOSE 5000

CMD ["python", "read_queue.py"]