# redis-slave1.conf

# 基本連線設定
port 6379
bind 0.0.0.0
protected-mode no

# 日誌寫檔
logfile "/data/redis-slave2.log"

# 主從複寫（master IP 會被 Sentinel 取代，但不設 Redis 不會啟動）
replicaof redis-master 6379

# 複寫相關設定
repl-diskless-sync yes
repl-diskless-sync-delay 10
repl-timeout 120
# repl-backlog-size 10mb

# 資料持久化
appendonly yes
